# SITE CONFIGURATION
#baseurl: "/Type-on-Strap"
#url: "https://sylhare.github.io"

# THEME-SPECIFIC CONFIGURATION
theme_settings:
  # Meta
  title: Samuel Fajreldines
  avatar: assets/img/photo.jpg
  favicon: assets/favicon.ico
  gravatar: # Email MD5 hash
  description: "Um blog sobre carreira, tecnologia, esportes e motivação." # used by search engines

  # Header and footer text
  header_text: > #two or three lines to describe your site
     <p>Um blog sobre carreira, tecnologia, esportes e motivação.</p>
  header_text_feature_image: assets/img/pexels/surfer.jpg

  # Icons
  rss: true
  email_address: samuelfaj@icloud.com # Full email address, e.g. "sam@example.com"
  behance:
  bitbucket:
  dribbble:
  facebook: samuel.fajreldines
  flickr:
  gitlab:
  github: "samuelfaj"
  google_plus:
  instagram: samuelfajreldines
  keybase:
  linkedin:  # Full URL
  pinterest:
  reddit:
  soundcloud:
  stack_exchange:  # Full URL
  steam:
  tumblr:
  twitter: # "twitter username"
  vimeo:
  wordpress:
  youtube:

  # Scripts / Features 
  google_analytics: # Tracking ID, e.g. "UA-000000-01"
  disqus_shortname:
  katex: true # Enable if using math markup
  portfolio: false
  search: true
  tags: false
  
  
  # Localization strings
  str_follow_on: "Siga"
  str_rss_follow: "Siga o RSS feed"
  str_email: "Email"
  str_next_post: "Próximo Post"
  str_previous_post: "Post Anterior"
  str_next_page: "Próx"
  str_previous_page: "Ant"
  str_continue_reading: "Continue lendo"
  str_javascript_required_disqus: "Please enable JavaScript to view comments."

  # Colours, typography and padding
  # Open the "_sass > base" folder, and open "_variables.scss"
  google_fonts: "Source+Sans+Pro:400,700,700italic,400italic"

  # Post navigation
  post_navigation: false

# PAGINATION
paginate: 5
paginate_path: "blog/page:num"

# PORTFOLIO
collections:
  portfolio:
    output: true
    permalink: /:categories/:name

# BUILD SETTINGS
markdown: kramdown
highlighter: rouge
sass:
  sass_dir: _sass
  style: :compressed
plugins: [jekyll-paginate, jekyll-seo-tag]
theme: type-on-strap # If using the theme as a jekyll theme gem
exclude: ["Gemfile", "Gemfile.lock", "type-on-strap.gemspec", "*.gem", "LICENSE", "README.md", "screenshot.png"]
